global_conf:
  layout: dot
  splines: ortho
  rankdir: LR
  ranksep: 10
  nodesep: 10
  esep: '+3'
  sep: '+3'

entity_conf:
  shape: Mrecord
  fontname: Noto Sans CJK JP Black
  fontsize: 20

group_conf:
  shape: Mrecord
  fontname: Noto Sans CJK JP Black
  fontsize: 40

arrow_map:
  has_many:
    fontsize: 40
    penwidth: 4
    minlen: 1
    headlabel: 'N'
    taillabel: '1'
    labelfloat: false
    dir: 'none'
  has_one:
    fontsize: 40
    penwidth: 4
    minlen: 1
    headlabel: '1'
    taillabel: '1'
    labelfloat: false
    dir: 'none'